import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="navbar">
          <p>My Project</p>
        </header>
        {children}
        <footer>
        </footer>
      </body>
    </html>
  )
}
